-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.WeatherType exposing (cloudy, id, moisture, temperature)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


cloudy : SelectionSet (Maybe Bool) Api.Object.WeatherType
cloudy =
    Object.selectionForField "(Maybe Bool)" "cloudy" [] (Decode.bool |> Decode.nullable)


id : SelectionSet (Maybe Api.ScalarCodecs.Id) Api.Object.WeatherType
id =
    Object.selectionForField "(Maybe ScalarCodecs.Id)" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)


moisture : SelectionSet (Maybe Int) Api.Object.WeatherType
moisture =
    Object.selectionForField "(Maybe Int)" "moisture" [] (Decode.int |> Decode.nullable)


temperature : SelectionSet (Maybe Int) Api.Object.WeatherType
temperature =
    Object.selectionForField "(Maybe Int)" "temperature" [] (Decode.int |> Decode.nullable)
